# Modulo 31: Ejercicios con DataFrames

### Ejercicio 1

Vamos a filtrar datos en un dataframe

1. Crearemos una lista de 50 valores aleatorios en enteros entre los valores 0 y 100
2. Convertiremos esta lista en un data frame de 5(filas)x10(columnas)
3. Filtraremos los datos del dataframe para visualizar sólo los valores que sean mayores que 50

In [7]:
import numpy as np
import pandas as pd
from math import ceil

In [17]:
valores = np.random.randint(0,100,50).reshape(5,10)
valores

array([[88,  0, 10, 95, 33, 97, 63, 44,  8, 72],
       [73, 32, 23, 13, 30, 50, 67, 12, 30, 31],
       [86, 25, 11, 16, 39, 95,  9, 17, 65, 89],
       [83, 23, 32,  9, 74, 22, 19, 78, 51, 77],
       [71, 64, 97, 81, 12, 40, 39, 13, 39, 45]])

In [18]:
dataframe = pd.DataFrame(valores)

In [19]:
dataframe

0   1   2   3   4   5   6   7   8   9
0  88   0  10  95  33  97  63  44   8  72
1  73  32  23  13  30  50  67  12  30  31
2  86  25  11  16  39  95   9  17  65  89
3  83  23  32   9  74  22  19  78  51  77
4  71  64  97  81  12  40  39  13  39  45

In [20]:
dataframe[dataframe>50]

0     1     2     3     4     5     6     7     8     9
0  88   NaN   NaN  95.0   NaN  97.0  63.0   NaN   NaN  72.0
1  73   NaN   NaN   NaN   NaN   NaN  67.0   NaN   NaN   NaN
2  86   NaN   NaN   NaN   NaN  95.0   NaN   NaN  65.0  89.0
3  83   NaN   NaN   NaN  74.0   NaN   NaN  78.0  51.0  77.0
4  71  64.0  97.0  81.0   NaN   NaN   NaN   NaN   NaN   NaN

### Ejercicio 2

* Crear 2 arrays con 9 números aleatorios enteros entre los valores 0 y 100
* Cambiar el formato de los arrays en una estructura de 3x3
* Crear dos dataframe con esos arrays
* Concatenar esos 2 dataframe

In [22]:
array1 = np.random.randint(0,100,9).reshape(3,3)
array2 = np.random.randint(0,100,9).reshape(3,3)

In [23]:
array1

array([[ 0, 80, 65],
       [91, 57, 43],
       [92, 81, 76]])

In [24]:
array2

array([[44, 77,  3],
       [47, 98, 20],
       [69, 76, 93]])

In [25]:
df1 = pd.DataFrame(array1)

In [26]:
df2 = pd.DataFrame(array2)

In [27]:
df1

0   1   2
0   0  80  65
1  91  57  43
2  92  81  76

In [28]:
df2

0   1   2
0  44  77   3
1  47  98  20
2  69  76  93

In [32]:
df3 = pd.concat([df1,df2],ignore_index=True) # "ignore_index=True" para que haga un nuevo índice
df3

0   1   2
0   0  80  65
1  91  57  43
2  92  81  76
3  44  77   3
4  47  98  20
5  69  76  93

In [33]:
df3B = pd.concat([df1,df2],axis=1) #Los concatenamos en el otro eje
df3B

0   1   2   0   1   2
0   0  80  65  44  77   3
1  91  57  43  47  98  20
2  92  81  76  69  76  93

In [ ]:
df3