# Modulo 26: Ejercicios

### Enunciado 1

Crear la función "pares" que devuelva una array de numeros pares entre dos valores pasados como parametros a la función (inicio y fin)

* Utillizar la función "pares" con los numeros 1 y 30
* Utilizar la función "pares" con los numeros 2 y 40

In [24]:
import numpy as np

def condition(numero):
    if (numero % 2 == 0):
        return True
    else:
        return False


def pares(inicio,fin):
    lista1 = list(range(inicio,fin+1,1))
    lista2 = list(filter(condition,lista1))
    
    array1 = np.array(lista2)    
    return array1

In [26]:
pares(1,30)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [27]:
pares(2,40)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [28]:
#Solución del curso:

def pares(inicio,fin):
    if (inicio % 2 == 0):
        array = np.arange(inicio,fin,2)
    else:
        inicio = inicio + 1
        array = np.arange(inicio,fin,2)
    return array

#### Enunciado 2

1. Crear una lista con numeros del 10 al 19
2. Crear otra lista con numeros del 50 al 59
3. Crear una matriz 2x10 con las listas anteriores
4. Crear otra matriz cuyos valores sean iguales a la matriz anterior multiplicados por 2

In [33]:
import numpy as pd

In [47]:
lista1 = range(10,20)

In [48]:
lista2= range(50,60)

In [49]:
matriz = np.array([lista1,lista2])

In [50]:
matriz.shape

(2, 10)

In [51]:
matriz2 = matriz * 2

In [52]:
matriz2

array([[ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118]])

#### Enunciado 3

1. Crear una lista con los valores numericos del 0 al 30
2. Crear una lista con los 10 primeros valores de la lista inicial
3. Crear una lista con los 10 últimos valores de la lista inicial
4. Crear un bucle que recorra esta última lista con los últimos elementos

In [53]:
lista_inicial = range(0,31)

In [60]:
primeros = lista_inicial[1:10]

In [65]:
ultimos = lista_inicial[20:30]
# Otra opción sería ultimos = lista_inicial[-10:]

In [66]:
for i in ultimos:
    print(i)

20
21
22
23
24
25
26
27
28
29
