# Modulo 25 - Numpy

## Creación de arrays

In [1]:
import numpy as np

In [2]:
np.zeros(4)

array([0., 0., 0., 0.])

In [3]:
np.ones(4)

array([1., 1., 1., 1.])

In [5]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(2,20,3) #Empieza en el 2, llega hasta el 20 y avanza de 3 en 3

array([ 2,  5,  8, 11, 14, 17])

In [9]:
lista = [1,2,3,4]
array1 = np.array(lista)

In [10]:
array1

array([1, 2, 3, 4])

In [11]:
lista1 = [1,2,3,4]
lista2 = [5,6,7,8]

In [12]:
lista_doble = (lista1,lista2)

In [13]:
lista_doble

([1, 2, 3, 4], [5, 6, 7, 8])

In [14]:
array_doble = np.array(lista_doble)

In [15]:
array_doble

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
array_doble.shape

(2, 4)

In [17]:
array_doble.dtype

dtype('int64')

#### Operaciones con arrays

In [18]:
array1 = np.array([1,2,3,4])

In [19]:
array1

array([1, 2, 3, 4])

In [22]:
array1*2 #Multiplica cada elemento por 2

array([2, 4, 6, 8])

In [23]:
array1 + 4 #Lo hace a cada elemento

array([5, 6, 7, 8])

In [24]:
lista1 = [1,2,3,4]
lista2 = [5,6,7,8]
lista_doble = (lista1,lista2)
array_doble = np.array(lista_doble)

In [25]:
array_doble

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
array_doble.shape

(2, 4)

In [27]:
array_doble + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [28]:
array_doble/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ]])

In [29]:
array_doble**2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [30]:
array_doble = array_doble + 4

In [31]:
array_doble

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Indexación con arrays

In [34]:
array = np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
#Hacemos un subconjunto de ese array

In [36]:
array[0:3] #Posición inicial hasta la posición final

array([0, 1, 2])

In [37]:
array[2:5]

array([2, 3, 4])

In [38]:
array[6:]

array([ 6,  7,  8,  9, 10])

In [39]:
array2 = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [40]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
array2[2]

array([7, 8, 9])

In [44]:
array2[0]

array([1, 2, 3])

In [46]:
array2[1][0] #Fila y columna

4

#### Matrices traspuestas (cambiar ordenadamente las filas por las columnas)

In [48]:
array = np.arange(15).reshape(3,5) 
#Creamos un array que tenga los elementos del 0 al 15 con la forma 3 filas y 5 columnas

In [49]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
array[1][1]

6

In [51]:
array_tras = array.T

In [52]:
array_tras

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#### Entrada y salida con arrays

In [55]:
array1 = np.arange(6)

In [56]:
array1

array([0, 1, 2, 3, 4, 5])

In [57]:
np.save('array1s',array1)

In [60]:
np.load('array1s.npy') #IMPORTANTE: Al recuperarlo debemos añadirle la extensión ".npy"

array([0, 1, 2, 3, 4, 5])

In [61]:
array1 = np.arange(6)
array1
array2 = np.arange(8)
array2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [62]:
array1

array([0, 1, 2, 3, 4, 5])

In [63]:
np.savez('arrays',x=array1,y=array2) #Salvamos 2 arrays, cada uno en una coordenada

In [65]:
array_recuperado = np.load('arrays.npz')

In [67]:
array_recuperado['x']

array([0, 1, 2, 3, 4, 5])

In [68]:
array_recuperado['y']

array([0, 1, 2, 3, 4, 5, 6, 7])

In [69]:
#Podemos guardar los arrays también en formato texto

In [70]:
np.savetxt('mificheroarray.txt',array2,delimiter=',')

In [71]:
array3 = np.loadtxt('mificheroarray.txt',delimiter=',')

In [72]:
array3

array([0., 1., 2., 3., 4., 5., 6., 7.])

####  Funciones en array

In [74]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [75]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [77]:
np.random.rand(5) #Genera numeros aleatorios

array([0.51296301, 0.76948178, 0.06504935, 0.76182899, 0.77556119])

In [81]:
lista = [5,6,7,8,9]
array2 = np.array(lista)

In [82]:
array2

array([5, 6, 7, 8, 9])

In [83]:
np.add(array,array2)

array([ 5,  7,  9, 11, 13])

In [85]:
np.maximum(array,array2)

array([5, 6, 7, 8, 9])